### ISSUE TITLE
Add info about app release into 'announcements' section

### ISSUE THREAD

**Issue by daolia** [voteflux/flux-website-v2#140]
Hi, can we add something like this into the announcements section? 

-- 

We are happy to announce we are launching the first version of our app in the coming months!

With the recent work put in by our small team of development volunteers and the backing of Securevote's [blockchain voting technology](https://secure.vote/), we're really looking forward to launching an alpha version of DigiPol: Australia's Digital Democracy.

This is something that could really affect how people participate in Australian politics-- even before we get a Flux member elected and have some real [Issue Based Direct Democracy](https://voteflux.org/about/vision-and-purpose/) inside government.

Here's a little bit of information to get excited about before the release in late April!

- **A Federal Parliamentary Mirror** that displays current and outstanding bills in both houses of Parliament. Users will be able to access explanatory memorandums and readings of bills, as tabled by current MPs. You'll be able to vote yes or no on each bill and will be given the results of their voting, by electorate and as a whole of Australia.

- **A Federal Issues Page** that displays a short, curated list of issues important to the Australian people. The issues will be curated from established interest groups, current petitioning systems 
as well as Flux member and general public input. Similar to voting on bills, users will be able to vote yes or no on an issue and see the results from their electorate and Australia. 

- **User Profiles** that are validated against the federal electoral roll. This will automatically assign their upper and lower house representatives and help display the most relevant information for their electorate.

Over the next few weeks, we will share more information to make it easy for Flux members to explain how it all works to their friends and family. [Become a member to stay in the loop.](https://voteflux.org/signup/?utm_content=nav~)

There's plenty more planned for future beta releases; issue creation, comments sections and the like. If you would like to know more about the technical implementation of the app, you can [inspect the code repository](https://github.com/voteflux/voting_app). 

If you are a developer, graphic designer or interested in UI/UX and would like to contribute, we would truly appreciate your input at this point in the process.  

For more information on how you can get involved, come and say hi on our [Discord server.](https://discord.io/FluxParty)

**Comment by XertroV** [comment]
@daolia this is great, thanks! Will get Ben et al on it.

**Comment by XertroV** [comment]
Also, if you want to be credited as (co-)author ("co-": presuming futher editing is done), let me know the name you'd like attributed (can PM on discord - @XertroV - if you'd like)

**Comment by daolia** [comment]
Cool, I submitted a pull request but now I can't find the code to edit it.  Did I do something wrong? I would like to link to these pages in the article for context: 

https://voteflux.org/about/how/
https://voteflux.org/about/what-is-flux/

Edit: Oh wait, I found it here! https://github.com/voteflux/flux-website-v2/pull/141/files I'm just not sure how to edit that with the new links. Advice appreciated...

Hi again. Never mind! I see that authors can't make changes! Anyway yes, I reckon it would be good to have those links in the article.

**Comment by XertroV** [comment]
Here's the branch: https://github.com/daolia/flux-website-v2/tree/patch-1
No, nothing wrong (well, I haven't reviewed the PR yet but looks good at first glance)

![image](https://user-images.githubusercontent.com/1046448/79854722-3a8d4700-840d-11ea-8073-6867abcb2477.png)

You can get back to your branch by clicking the name in the PR as above -- but the branch is on _your_ copy of `flux-website-v2` rather than this repo; that might be what tripped you up.

* time passes *

.. Ahh, should have finished reading your comment 🤦 - glad you got it working

You can edit the file again from the PR like so:

![image](https://user-images.githubusercontent.com/1046448/79854913-9061ef00-840d-11ea-95c5-69c1cf80c505.png)
