### ISSUE TITLE
WA posts should show up on front page

### ISSUE THREAD

**Issue by XertroV** [voteflux/flux-website-v2#164]
I think we should combine WA posts and normal posts so they all show up on the front page.

I also think we should tag WA posts with some tag so _only_ those posts show up on the WA page.

There's a small amount of structural rejiggering and I'll need to move all the WA posts to the _posts folder.

Thoughts @okdaithi ?

**Comment by okdaithi** [comment]
Sounds good to me.
An incentive for us to generate content - which is what we need.
