### ISSUE TITLE
Hamburger menu is broken on mobiles

### ISSUE THREAD

**Issue by TomSesselmann** [voteflux/flux-website-v2#4]
In https://github.com/voteflux/vote-flux-v2/blob/master/_includes/navbar.html#L89

`assign pages_list` needs to be changed to `assign all_pages`

Looks like it broke here https://github.com/voteflux/vote-flux-v2/commit/f7fa4eeff2c0c8c36d41f2b936377c579c44bbc0

@XertroV

**Comment by XertroV** [comment]
Fixed by #5
